### PR TITLE
10 -- Journal: week 2

### PR DESCRIPTION
**Pull request by cmauban**

### CODE REVIEW

**Comment by Ricecoder** [comment]
I like all of the examples you give to help explain encapsulation and not needing to know everything in order to work on something. Good work! :+1:

**Comment by ericksonk** [comment]
Your definition of the DOM helps a lot! Still trying to grasp _Encapsulation_ but it seems you you have a good understanding :+1:

**Comment by ericquayson** [comment]
:+1: Good work. I liked your example for the encapsulation.

**Comment by ericksonk** [comment]
I like the section you added about your overall feelings- great way to close. :+1:

**Comment by boshnivolo** [comment]
I like your ending paragraph. I also struggle with translating JavaScript into English. But DOM becoming clearer does help understanding it better. :+1: Good essay!

**Pull request merged**
