### PR TITLE
Journal week 3 into master

### PR DESCRIPTION
**Pull request by cmauban**

### CODE REVIEW

**Comment by Ricecoder** [comment]
Very informative tutorial. I will have to look back on it next time I am trying to center something. I also am confused by the pseudo elements. Good starting point! :+1:

**Comment by ericksonk** [comment]
I always seem to have problems centering boxes so thanks for clearing things up :+1: 

Pseudo elements confuse me too...

**Comment by jmcreasman** [comment]
Very helpful tutorial! :+1:

**Comment by jeffworley** [comment]
Looks like a solid rough draft!  The reflection was insightful and your tutorial has a good scope.  I look forward to seeing you build out the steps in the tutorial and explaining what each property you are interacting with does and why you chose it.  :+1:

**Comment by Ricecoder** [comment]
:+1: Looking good! I am also a fan of code comments to keep things clean and organized.

**Comment by ericksonk** [comment]
Try rewording the sentence about positioning and margins for your final draft, its a little confusing. Other than that everything looks good :+1:

**Comment by ShayHall** [comment]
I see you have a few reviews...  Here's another.

I liked "Throughout the week my CSS code became cleaner and cleaner."  Isn't that the goal!?  Good succinct reflection.

I also like that your tutorial is short but specific.  It makes that one issue (that can be a big one) seem manageable.  You're on point :round_pushpin:

**Comment by karjac14** [comment]
This is a good read! It seems most of us enjoyed CSS more than JS. Looking forward to hear more a-ha moments of yours! :+1:

**Comment by boshnivolo** [comment]
I like your reflective piece! I also remember my first "ah-ha" moment with CSS haha :+1:

**Comment by rosalsm** [comment]
I feel the same about week 3. CSS was fun but it is still fun, keep going! :+1:

**Pull request merged**
